TreeTransportMissionWrongSellingStationEvent = {}
local TreeTransportMissionWrongSellingStationEvent_mt = Class(TreeTransportMissionWrongSellingStationEvent, Event)
InitStaticEventClass(TreeTransportMissionWrongSellingStationEvent, "TreeTransportMissionWrongSellingStationEvent")
function TreeTransportMissionWrongSellingStationEvent.emptyNew()
	local self = Event.new(TreeTransportMissionWrongSellingStationEvent_mt)
	return self
end
function TreeTransportMissionWrongSellingStationEvent.new()
	local self = TreeTransportMissionWrongSellingStationEvent.emptyNew()
	return self
end
function TreeTransportMissionWrongSellingStationEvent:readStream(streamId, connection)
	self:run(connection)
end
function TreeTransportMissionWrongSellingStationEvent:writeStream(streamId, connection) end
function TreeTransportMissionWrongSellingStationEvent:run(connection)
	g_currentMission:addIngameNotification(FSBaseMission.INGAME_NOTIFICATION_CRITICAL, g_i18n:getText("ingameNotification_treeTransportWrongSellingStationWarning"))
end
