DynamicDataGridTest = {}
function DynamicDataGridTest.test_constructor()
	Assert.throwsError(function()
		DynamicDataGrid.new(160, nil)
	end, "Passing in a nil tile size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(0, nil)
	end, "Passing in a zero tile size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(true, nil)
	end, "Passing in a non-number tile size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(nil, 16)
	end, "Passing in a nil size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(nil, 0)
	end, "Passing in a zero size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(nil, true)
	end, "Passing in a non-number size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(160, 16, 1)
	end, "Passing in only an x position did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(160, 16, true)
	end, "Passing in a non-number x position did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(160, 16, nil, 1)
	end, "Passing in only an z position did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(160, 16, 0, true)
	end, "Passing in a non-number z position did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(160, 16, 0, 0, true)
	end, "Passing in a non-function constructor did not throw an error.")
	local v1_ = DynamicDataGrid.new(320, 16)
	Assert.areEqual(320, v1_.size, "Size did not match the given size.")
	Assert.areEqual(16, v1_.tileSize, "Tile Size did not match the given size.")
	Assert.areEqual(20, v1_.rowColumnCount, "Number of rows/columns was invalid from given size.")
end
function DynamicDataGridTest.test_positionSnapping()
	local v2_ = DynamicDataGrid.new(400, 16, 200, 200)
	local v3_, v4_ = v2_:getGridSnappedPosition(0, 0)
	Assert.areEqual(v3_, v2_.tileSize / 2)
	Assert.areEqual(v4_, v2_.tileSize / 2)
	local v5_, v6_ = v2_:getGridSnappedPosition(v2_.tileSize / 2, v2_.tileSize / 2)
	Assert.areEqual(v5_, v2_.tileSize / 2)
	Assert.areEqual(v6_, v2_.tileSize / 2)
	local v7_, v8_ = v2_:getGridSnappedPosition(v2_.tileSize - 1, v2_.tileSize - 1)
	Assert.areEqual(v7_, v2_.tileSize / 2)
	Assert.areEqual(v8_, v2_.tileSize / 2)
	local v9_, v10_ = v2_:getGridSnappedPosition(v2_.tileSize, v2_.tileSize)
	Assert.areEqual(v9_, v2_.tileSize * 1.5)
	Assert.areEqual(v10_, v2_.tileSize * 1.5)
	local v11_, v12_ = v2_:getGridSnappedPosition(-v2_.tileSize, -v2_.tileSize)
	Assert.areEqual(v11_, v2_.tileSize / -2)
	Assert.areEqual(v12_, v2_.tileSize / -2)
	local v13_, v14_ = v2_:getGridSnappedPosition(0, -1)
	Assert.areEqual(v13_, v2_.tileSize / 2)
	Assert.areEqual(v14_, v2_.tileSize / -2)
end
function DynamicDataGridTest.test_gridIndices()
	local v15_ = DynamicDataGrid.new(400, 16, 200, 200)
	local v16_, v17_ = v15_:getGridIndicesByWorldPosition(0, 0)
	Assert.areEqual(v16_, 1)
	Assert.areEqual(v17_, 1)
	local v18_, v19_ = v15_:getGridIndicesByWorldPosition(v15_.tileSize / 2, v15_.tileSize / 2)
	Assert.areEqual(v18_, 1)
	Assert.areEqual(v19_, 1)
	local v20_, v21_ = v15_:getGridIndicesByWorldPosition(v15_.tileSize - 1, v15_.tileSize - 1)
	Assert.areEqual(v20_, 1)
	Assert.areEqual(v21_, 1)
	local v22_, v23_ = v15_:getGridIndicesByWorldPosition(v15_.tileSize, v15_.tileSize)
	Assert.areEqual(v22_, 2)
	Assert.areEqual(v23_, 2)
	local v24_, v25_ = v15_:getGridIndicesByWorldPosition(v15_.size / 2 - 1, v15_.size / 2 - 1)
	Assert.areEqual(v24_, v15_.centreIndex)
	Assert.areEqual(v25_, v15_.centreIndex)
	local v26_, v27_ = v15_:getGridIndicesByWorldPosition(v15_.size - 1, v15_.size - 1)
	Assert.areEqual(v26_, v15_.rowColumnCount)
	Assert.areEqual(v27_, v15_.rowColumnCount)
	local v28_, v29_ = v15_:getGridIndicesByWorldPosition(0, v15_.tileSize)
	Assert.areEqual(v28_, 1)
	Assert.areEqual(v29_, 2)
end

-- Local values: dataGrid, testCellX, testCellZ, testWorldX, testWorldZ
function DynamicDataGridTest:test_localIndices()
	local v30_ = DynamicDataGrid.new(400, 16, 200, 200)
	local v31_, v32_ = v30_:getLocalIndicesByWorldPosition(v30_.size / 2 - 1, v30_.size / 2 - 1)
	Assert.areEqual(v31_, 0)
	Assert.areEqual(v32_, 0)
	local v33_, v34_ = v30_:getWorldPositionByLocalIndices(0, 0)
	Assert.areEqual(v33_, v30_.size / 2)
	Assert.areEqual(v34_, v30_.size / 2)
	local v35_, v36_ = v30_:getLocalIndicesByWorldPosition(0, 0)
	Assert.areEqual(v35_, v30_.localStartIndex)
	Assert.areEqual(v36_, v30_.localStartIndex)
	local v37_, v38_ = v30_:getWorldPositionByLocalIndices(v30_.localStartIndex, v30_.localStartIndex)
	Assert.areEqual(v37_, v30_.tileSize / 2)
	Assert.areEqual(v38_, v30_.tileSize / 2)
	local v39_, v40_ = v30_:getLocalIndicesByWorldPosition(v30_.size - 1, v30_.size - 1)
	Assert.areEqual(v39_, v30_.localEndIndex)
	Assert.areEqual(v40_, v30_.localEndIndex)
	local v41_, v42_ = v30_:getWorldPositionByLocalIndices(v30_.localEndIndex, v30_.localEndIndex)
	Assert.areEqual(v41_, v30_.size - v30_.tileSize / 2)
	Assert.areEqual(v42_, v30_.size - v30_.tileSize / 2)
	local v43_, v44_ = v30_:getLocalIndicesByWorldPosition(0, -1)
	Assert.areEqual(v43_, v30_.localStartIndex)
	Assert.areEqual(v44_, v30_.localStartIndex - 1)
	local v45_, v46_ = v30_:getWorldPositionByLocalIndices(v30_.localStartIndex, v30_.localStartIndex - 1)
	Assert.areEqual(v45_, v30_.tileSize / 2)
	Assert.areEqual(v46_, v30_.tileSize / -2)
end

-- Local values: dataGrid, testLocalX, testLocalZ
function DynamicDataGridTest:test_localPositions()
	local v47_ = DynamicDataGrid.new(400, 16, 200, 200)
	local v48_, v49_ = v47_:getGridSnappedPositionByLocalIndices(0, 0)
	Assert.areEqual(v48_, v47_.tileSize / 2)
	Assert.areEqual(v49_, v47_.tileSize / 2)
	local v50_, v51_ = v47_:getGridSnappedPositionByLocalIndices(1, 1)
	Assert.areEqual(v50_, v47_.tileSize * 1.5)
	Assert.areEqual(v51_, v47_.tileSize * 1.5)
	local v52_, v53_ = v47_:getGridSnappedPositionByLocalIndices(-1, -1)
	Assert.areEqual(v52_, v47_.tileSize / -2)
	Assert.areEqual(v53_, v47_.tileSize / -2)
	local v54_, v55_ = v47_:getGridSnappedPositionByLocalIndices(-1, 1)
	Assert.areEqual(v54_, v47_.tileSize / -2)
	Assert.areEqual(v55_, v47_.tileSize * 1.5)
end
function DynamicDataGridTest.test_size()
	for v56_ = 0, 32 do
		local v57_ = DynamicDataGrid.new(200 + v56_, 16)
		DynamicDataGridTest.testEntireGrid(v57_)
	end
end

-- Local values: localRowIndex, localColumnIndex, rowIndex, columnIndex, rawCell, localCell, worldX, worldZ, localIndexX, localIndexZ, worldCell
function DynamicDataGridTest.testEntireGrid(dataGrid)
	local v59_ = dataGrid.localStartIndex
	local v60_ = dataGrid.localStartIndex
	for v61_ = 1, dataGrid.rowColumnCount do
		for v62_ = 1, dataGrid.rowColumnCount do
			local v63_ = dataGrid.grid[v62_][v61_]
			Assert.isNotNil(v63_, string.format("Indexed cell at %d, %d was nil.", v62_, v61_))
			local v64_ = dataGrid:getCellFromLocalIndices(v60_, v59_)
			Assert.areEqual(v63_, v64_, "Raw indexed cell did not match locally indexed cell at %d, %d", v60_, v59_)
			local v65_, v66_ = dataGrid:getWorldPositionByLocalIndices(v60_, v59_)
			local v67_, v68_ = dataGrid:getLocalIndicesByWorldPosition(v65_, v66_)
			Assert.areEqual(v67_, v60_)
			Assert.areEqual(v68_, v59_)
			local v69_ = dataGrid:getCellFromWorldPosition(v65_, v66_)
			Assert.areEqual(v64_, v69_)
			Assert.areEqual(dataGrid:getCellFromWorldPosition(v65_ + (dataGrid.tileSize / 2 - 1), v66_ + (dataGrid.tileSize / 2 - 1)), v69_)
			Assert.areEqual(dataGrid:getCellFromWorldPosition(v65_ - dataGrid.tileSize / 2, v66_ - dataGrid.tileSize / 2), v69_)
			v60_ = v60_ + 1
		end
		v60_ = dataGrid.localStartIndex
		v59_ = v59_ + 1
	end
end
