DynamicDataGridTest = {}
function DynamicDataGridTest.test_constructor()
	Assert.throwsError(function()
		DynamicDataGrid.new(160, nil)
	end, "Passing in a nil tile size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(0, nil)
	end, "Passing in a zero tile size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(true, nil)
	end, "Passing in a non-number tile size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(nil, 16)
	end, "Passing in a nil size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(nil, 0)
	end, "Passing in a zero size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(nil, true)
	end, "Passing in a non-number size did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(160, 16, 1)
	end, "Passing in only an x position did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(160, 16, true)
	end, "Passing in a non-number x position did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(160, 16, nil, 1)
	end, "Passing in only an z position did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(160, 16, 0, true)
	end, "Passing in a non-number z position did not throw an error.")
	Assert.throwsError(function()
		DynamicDataGrid.new(160, 16, 0, 0, true)
	end, "Passing in a non-function constructor did not throw an error.")
	local dataGrid = DynamicDataGrid.new(320, 16)
	Assert.areEqual(320, dataGrid.size, "Size did not match the given size.")
	Assert.areEqual(16, dataGrid.tileSize, "Tile Size did not match the given size.")
	Assert.areEqual(20, dataGrid.rowColumnCount, "Number of rows/columns was invalid from given size.")
end
function DynamicDataGridTest.test_positionSnapping()
	local dataGrid = DynamicDataGrid.new(400, 16, 200, 200)
	local snappedWorldX, snappedWorldZ = dataGrid:getGridSnappedPosition(0, 0)
	Assert.areEqual(snappedWorldX, dataGrid.tileSize / 2)
	Assert.areEqual(snappedWorldZ, dataGrid.tileSize / 2)
	snappedWorldX, snappedWorldZ = dataGrid:getGridSnappedPosition(dataGrid.tileSize / 2, dataGrid.tileSize / 2)
	Assert.areEqual(snappedWorldX, dataGrid.tileSize / 2)
	Assert.areEqual(snappedWorldZ, dataGrid.tileSize / 2)
	snappedWorldX, snappedWorldZ = dataGrid:getGridSnappedPosition(dataGrid.tileSize - 1, dataGrid.tileSize - 1)
	Assert.areEqual(snappedWorldX, dataGrid.tileSize / 2)
	Assert.areEqual(snappedWorldZ, dataGrid.tileSize / 2)
	snappedWorldX, snappedWorldZ = dataGrid:getGridSnappedPosition(dataGrid.tileSize, dataGrid.tileSize)
	Assert.areEqual(snappedWorldX, dataGrid.tileSize * 1.5)
	Assert.areEqual(snappedWorldZ, dataGrid.tileSize * 1.5)
	snappedWorldX, snappedWorldZ = dataGrid:getGridSnappedPosition(-dataGrid.tileSize, -dataGrid.tileSize)
	Assert.areEqual(snappedWorldX, dataGrid.tileSize / -2)
	Assert.areEqual(snappedWorldZ, dataGrid.tileSize / -2)
	snappedWorldX, snappedWorldZ = dataGrid:getGridSnappedPosition(0, -1)
	Assert.areEqual(snappedWorldX, dataGrid.tileSize / 2)
	Assert.areEqual(snappedWorldZ, dataGrid.tileSize / -2)
end
function DynamicDataGridTest.test_gridIndices()
	local dataGrid = DynamicDataGrid.new(400, 16, 200, 200)
	local testCellX, testCellZ = dataGrid:getGridIndicesByWorldPosition(0, 0)
	Assert.areEqual(testCellX, 1)
	Assert.areEqual(testCellZ, 1)
	testCellX, testCellZ = dataGrid:getGridIndicesByWorldPosition(dataGrid.tileSize / 2, dataGrid.tileSize / 2)
	Assert.areEqual(testCellX, 1)
	Assert.areEqual(testCellZ, 1)
	testCellX, testCellZ = dataGrid:getGridIndicesByWorldPosition(dataGrid.tileSize - 1, dataGrid.tileSize - 1)
	Assert.areEqual(testCellX, 1)
	Assert.areEqual(testCellZ, 1)
	testCellX, testCellZ = dataGrid:getGridIndicesByWorldPosition(dataGrid.tileSize, dataGrid.tileSize)
	Assert.areEqual(testCellX, 2)
	Assert.areEqual(testCellZ, 2)
	testCellX, testCellZ = dataGrid:getGridIndicesByWorldPosition(dataGrid.size / 2 - 1, dataGrid.size / 2 - 1)
	Assert.areEqual(testCellX, dataGrid.centreIndex)
	Assert.areEqual(testCellZ, dataGrid.centreIndex)
	testCellX, testCellZ = dataGrid:getGridIndicesByWorldPosition(dataGrid.size - 1, dataGrid.size - 1)
	Assert.areEqual(testCellX, dataGrid.rowColumnCount)
	Assert.areEqual(testCellZ, dataGrid.rowColumnCount)
	testCellX, testCellZ = dataGrid:getGridIndicesByWorldPosition(0, dataGrid.tileSize)
	Assert.areEqual(testCellX, 1)
	Assert.areEqual(testCellZ, 2)
end
function DynamicDataGridTest:test_localIndices()
	local dataGrid = DynamicDataGrid.new(400, 16, 200, 200)
	local testCellX, testCellZ = dataGrid:getLocalIndicesByWorldPosition(dataGrid.size / 2 - 1, dataGrid.size / 2 - 1)
	Assert.areEqual(testCellX, 0)
	Assert.areEqual(testCellZ, 0)
	local testWorldX, testWorldZ = dataGrid:getWorldPositionByLocalIndices(0, 0)
	Assert.areEqual(testWorldX, dataGrid.size / 2)
	Assert.areEqual(testWorldZ, dataGrid.size / 2)
	testCellX, testCellZ = dataGrid:getLocalIndicesByWorldPosition(0, 0)
	Assert.areEqual(testCellX, dataGrid.localStartIndex)
	Assert.areEqual(testCellZ, dataGrid.localStartIndex)
	testWorldX, testWorldZ = dataGrid:getWorldPositionByLocalIndices(dataGrid.localStartIndex, dataGrid.localStartIndex)
	Assert.areEqual(testWorldX, dataGrid.tileSize / 2)
	Assert.areEqual(testWorldZ, dataGrid.tileSize / 2)
	testCellX, testCellZ = dataGrid:getLocalIndicesByWorldPosition(dataGrid.size - 1, dataGrid.size - 1)
	Assert.areEqual(testCellX, dataGrid.localEndIndex)
	Assert.areEqual(testCellZ, dataGrid.localEndIndex)
	testWorldX, testWorldZ = dataGrid:getWorldPositionByLocalIndices(dataGrid.localEndIndex, dataGrid.localEndIndex)
	Assert.areEqual(testWorldX, dataGrid.size - dataGrid.tileSize / 2)
	Assert.areEqual(testWorldZ, dataGrid.size - dataGrid.tileSize / 2)
	testCellX, testCellZ = dataGrid:getLocalIndicesByWorldPosition(0, -1)
	Assert.areEqual(testCellX, dataGrid.localStartIndex)
	Assert.areEqual(testCellZ, dataGrid.localStartIndex - 1)
	testWorldX, testWorldZ = dataGrid:getWorldPositionByLocalIndices(dataGrid.localStartIndex, dataGrid.localStartIndex - 1)
	Assert.areEqual(testWorldX, dataGrid.tileSize / 2)
	Assert.areEqual(testWorldZ, dataGrid.tileSize / -2)
end
function DynamicDataGridTest:test_localPositions()
	local dataGrid = DynamicDataGrid.new(400, 16, 200, 200)
	local testLocalX, testLocalZ = dataGrid:getGridSnappedPositionByLocalIndices(0, 0)
	Assert.areEqual(testLocalX, dataGrid.tileSize / 2)
	Assert.areEqual(testLocalZ, dataGrid.tileSize / 2)
	testLocalX, testLocalZ = dataGrid:getGridSnappedPositionByLocalIndices(1, 1)
	Assert.areEqual(testLocalX, dataGrid.tileSize * 1.5)
	Assert.areEqual(testLocalZ, dataGrid.tileSize * 1.5)
	testLocalX, testLocalZ = dataGrid:getGridSnappedPositionByLocalIndices(-1, -1)
	Assert.areEqual(testLocalX, dataGrid.tileSize / -2)
	Assert.areEqual(testLocalZ, dataGrid.tileSize / -2)
	testLocalX, testLocalZ = dataGrid:getGridSnappedPositionByLocalIndices(-1, 1)
	Assert.areEqual(testLocalX, dataGrid.tileSize / -2)
	Assert.areEqual(testLocalZ, dataGrid.tileSize * 1.5)
end
function DynamicDataGridTest.test_size()
	for extraSize = 0, 32 do
		local dataGrid = DynamicDataGrid.new(200 + extraSize, 16)
		DynamicDataGridTest.testEntireGrid(dataGrid)
	end
end
function DynamicDataGridTest.testEntireGrid(dataGrid)
	local localRowIndex = dataGrid.localStartIndex
	local localColumnIndex = dataGrid.localStartIndex
	for rowIndex = 1, dataGrid.rowColumnCount do
		for columnIndex = 1, dataGrid.rowColumnCount do
			local rawCell = dataGrid.grid[columnIndex][rowIndex]
			Assert.isNotNil(rawCell, string.format("Indexed cell at %d, %d was nil.", columnIndex, rowIndex))
			local localCell = dataGrid:getCellFromLocalIndices(localColumnIndex, localRowIndex)
			Assert.areEqual(rawCell, localCell, "Raw indexed cell did not match locally indexed cell at %d, %d", localColumnIndex, localRowIndex)
			local worldX, worldZ = dataGrid:getWorldPositionByLocalIndices(localColumnIndex, localRowIndex)
			local localIndexX, localIndexZ = dataGrid:getLocalIndicesByWorldPosition(worldX, worldZ)
			Assert.areEqual(localIndexX, localColumnIndex)
			Assert.areEqual(localIndexZ, localRowIndex)
			local worldCell = dataGrid:getCellFromWorldPosition(worldX, worldZ)
			Assert.areEqual(localCell, worldCell)
			Assert.areEqual(dataGrid:getCellFromWorldPosition(worldX + (dataGrid.tileSize / 2 - 1), worldZ + (dataGrid.tileSize / 2 - 1)), worldCell)
			Assert.areEqual(dataGrid:getCellFromWorldPosition(worldX - dataGrid.tileSize / 2, worldZ - dataGrid.tileSize / 2), worldCell)
			localColumnIndex = localColumnIndex + 1
		end
		localColumnIndex = dataGrid.localStartIndex
		localRowIndex = localRowIndex + 1
	end
end
