StringTest = {}
function StringTest.test_isNilOrWhitespace()
	Assert.isTrue(string.isNilOrWhitespace(nil), "Nil string returned false!")
	Assert.isTrue(string.isNilOrWhitespace(""), "Empty string returned false!")
	Assert.isTrue(string.isNilOrWhitespace(" "), "Whitespace string returned false!")
	Assert.isTrue(string.isNilOrWhitespace("\n\r\t"), "Whitespace string (newline, carriage return, tab) returned false!")
	Assert.isFalse(string.isNilOrWhitespace("a", "Non-whitespace string returned true!"))
	Assert.isFalse(string.isNilOrWhitespace("   a   ", "Non-whitespace string returned true!"))
	Assert.isFalse(string.isNilOrWhitespace("a   ", "Non-whitespace string returned true!"))
	Assert.isFalse(string.isNilOrWhitespace("   a", "Non-whitespace string returned true!"))
end
function StringTest.test_contains()
	Assert.throwsError(function()
		local str = nil
		local substring = ""
		string.contains(nil, "")
	end, "Nil as string argument does not raise an error")
	Assert.throwsError(function()
		local substring = nil
		string.contains("", nil)
	end, "Nil as substring argument does not raise an error")
	Assert.isTrue(string.contains("", ""), "empty string does not contain empty string")
	Assert.isFalse(string.contains("", " "), "empty string contains white space")
	Assert.isTrue(string.contains("a", "a"), "present substring was not found")
	Assert.isFalse(string.contains("a", "b"), "non-present substring was not found")
	Assert.isTrue(string.contains("a\195\164\195\188a", "\195\164\195\188"), "Non-ASCII substring characters were not found")
	Assert.isFalse(string.contains("a\195\164a", "\195\164\195\188"), "Non-present Non-ASCII substring characters were found")
	Assert.isTrue(string.contains("a\nb", "\n"), "Newline substring was not found")
	local str, _firstChar, _lastChar, randomChar = StringTest.generateRandomStr(100000)
	Assert.isTrue(string.contains(str, randomChar), "returns false for char '%s' (%d)", randomChar, string.byte(randomChar))
	Assert.isTrue(string.contains("abc", ".c"))
	Assert.isFalse(string.contains("abc", "b.c"))
	Assert.isFalse(string.contains("abc", ".c", true))
	Assert.isTrue(string.contains("abc", "bc", true))
	Assert.throwsError(function()
		string.contains("abc", "bc", 10)
	end, "Number value for 'plain' argument does not raise an error")
	Assert.throwsError(function()
		string.contains("abc", "bc", {})
	end, "Table value for 'plain' argument does not raise an error")
	Assert.throwsError(function()
		string.contains("abc", "bc", "yes")
	end, "String value for 'plain' argument does not raise an error")
end
function StringTest.test_split()
	Assert.throwsError(function()
		local str = nil
		string.split(nil)
	end, "Nil string does not raise an error")
	Assert.throwsError(function()
		string.split("a b c", true)
	end, "boolean separator argument does not raise an error")
	Assert.areEqual(#string.split(""), 1)
	Assert.areEqual(string.split("abc")[1], "abc")
	Assert.areEqual(#string.split("a,b,c"), 3)
	local strs = {}
	for i = 1, 1000 do
		table.insert(strs, "bla bla bla, many words, much wow\nHansi did it \t \195\164\195\182\195\188")
	end
	local str = table.concat(strs, "|")
	Assert.areEqual(#string.split(str, "|"), #strs, "number of strings after split was not the same as before concat")
	Assert.areEqual(#string.split("a,b,c", ",", function(str)
		return nil
	end), 0, "result was not empty table when filter function returned nil for every element")
	Assert.areEqual(
		string.split("a,b,c", ",", function(str)
			return "override"
		end)[3],
		"override",
		"result element was not equal to filter function return"
	)
	Assert.throwsError(function()
		string.split("a b c", " ", true)
	end, "boolean filterFunction argument does not raise an error")
end
function StringTest.test_namedFormat()
	Assert.throwsError(function()
		local formatStr = nil
		string.namedFormat(nil)
	end, "Nil format string with nil args does not raise an error")
	Assert.throwsError(function()
		local formatStr = nil
		string.namedFormat(nil, "")
	end, "Nil format string with args does not raise an error")
	Assert.areEqual(string.namedFormat(""), "", "empty format string does not return empty string")
	Assert.areEqual(string.namedFormat("%{var2}s %{var1}.4f", "var1", 3.14159, "var2", "val2"), "val2 3.1416")
	Assert.throwsError(function()
		string.namedFormat("%{}s", "", "val1")
	end, "empty variable name does not raise an error")
	Assert.throwsError(function()
		string.namedFormat("%{ }s", " ", "val1")
	end, "whitespace variable name does not raise an error")
	Assert.throwsError(function()
		local args = { "%{var1}s", "var1" }
		string.namedFormat(unpack(args))
	end, "missing value for named argument does not raise an error")
	Assert.throwsError(function()
		local args = { "%{var1}s", "var2", "val2" }
		string.namedFormat(unpack(args))
	end, "missing named argument does not raise an error")
	Assert.throwsError(function()
		string.namedFormat("%{var1}s %{var2}", "var1", "var2", "val2", "test")
	end, "missing named argument does not raise an error")
end
function StringTest.test_getRadians()
	Assert.throwsError(function()
		string.getRadians({})
	end, "Table value for 'str' argument does not raise an error")
	Assert.throwsError(function()
		string.getRadians(true)
	end, "Boolean value for 'str' argument does not raise an error")
	Assert.throwsError(function()
		string.getRadians(5)
	end, "Number value for 'str' argument does not raise an error")
	Assert.areRoughlyEqual(string.getRadians("0")[1], 0)
	Assert.areRoughlyEqual(string.getRadians("90")[1], 1.5707963267948966)
	Assert.areRoughlyEqual(string.getRadians("180")[1], 3.141592653589793)
	Assert.areRoughlyEqual(string.getRadians("270")[1], 4.71238898038469)
	Assert.areRoughlyEqual(string.getRadians("360")[1], 6.283185307179586)
	Assert.areRoughlyEqual(string.getRadians("720")[1], 12.566370614359172)
	Assert.areRoughlyEqual(string.getRadians("-0")[1], 0)
	Assert.areRoughlyEqual(string.getRadians("-90")[1], -1.5707963267948966)
	Assert.areRoughlyEqual(string.getRadians("-180")[1], -3.141592653589793)
	Assert.areRoughlyEqual(string.getRadians("-270")[1], -4.71238898038469)
	Assert.areRoughlyEqual(string.getRadians("-360")[1], -6.283185307179586)
	Assert.areRoughlyEqual(string.getRadians("-720")[1], -12.566370614359172)
	Assert.areEqual(#string.getRadians(""), 0)
	Assert.areEqual(#string.getRadians("0"), 1)
	Assert.areEqual(#string.getRadians("0 1"), 2)
	Assert.areEqual(#string.getRadians("0 1 2 3 4 5"), 6)
	Assert.areEqual(string.getRadians(nil), nil)
	Assert.areEqual(string.getRadians(nil, 3), nil)
	Assert.areEqual(string.getRadians("", 3), nil)
	Assert.areEqual(string.getRadians("0 90", 3), nil)
	Assert.throwsError(function()
		string.getRadians("150", true)
	end, "Boolean value for 'num' argument does not raise an error")
	Assert.throwsError(function()
		string.getRadians("150", {})
	end, "Table value for 'num' argument does not raise an error")
	Assert.throwsError(function()
		string.getRadians("150", "yes")
	end, "String value for 'num' argument does not raise an error")
end
function StringTest.test_getVector()
	Assert.throwsError(function()
		string.getVector({})
	end, "Table value for 'str' argument does not raise an error")
	Assert.throwsError(function()
		string.getVector(true)
	end, "Boolean value for 'str' argument does not raise an error")
	Assert.throwsError(function()
		string.getVector(5)
	end, "Number value for 'str' argument does not raise an error")
	Assert.isType(string.getVector(""), "table")
	Assert.areEqual(#string.getVector(""), 0)
	Assert.areEqual(table.size(string.getVector("")), 0)
	Assert.areEqual(string.getVector(), nil)
	Assert.areEqual(string.getVector(nil), nil)
	Assert.areEqual(string.getVector(nil, nil), nil)
	Assert.areEqual(string.getVector("a"), nil)
	Assert.areEqual(string.getVector("a", nil), nil)
	Assert.areEqual(string.getVector("true", nil), nil)
	Assert.areEqual(string.getVector("{}", nil), nil)
	Assert.areEqual(string.getVector("3.4.5", nil), nil)
	Assert.areEqual(string.getVector("1 2", 1), nil)
	Assert.areEqual(string.getVector("1 2", 3), nil)
	Assert.areEqual(string.getVector("1 2 "), nil)
	Assert.areEqual(string.getVector(" 1 2"), nil)
	Assert.areEqual(string.getVector(" 1 2 "), nil)
	Assert.areEqual(string.getVector("1  2"), nil)
	Assert.throwsError(function()
		string.getVector("150 10", true)
	end, "Boolean value for 'num' argument does not raise an error")
	Assert.throwsError(function()
		string.getVector("150 10", {})
	end, "Table value for 'num' argument does not raise an error")
	Assert.throwsError(function()
		string.getVector("150 10", "yes")
	end, "String value for 'num' argument does not raise an error")
	Assert.areEqual(string.getVector("50")[1], 50)
	Assert.areEqual(string.getVector("50", nil)[1], 50)
	Assert.areEqual(string.getVector("50", 1)[1], 50)
	Assert.areEqual(string.getVector("-50")[1], -50)
	Assert.areEqual(string.getVector("-50", nil)[1], -50)
	Assert.areEqual(string.getVector("-50", 1)[1], -50)
	Assert.areRoughlyEqual(string.getVector("1.234")[1], 1.234)
	Assert.areRoughlyEqual(string.getVector("1.234", nil)[1], 1.234)
	Assert.areRoughlyEqual(string.getVector("1.234", 1)[1], 1.234)
	Assert.areRoughlyEqual(string.getVector(".234")[1], 0.234)
	Assert.areRoughlyEqual(string.getVector("-.234")[1], -0.234)
	Assert.areRoughlyEqual(string.getVector("-1.234")[1], -1.234)
	Assert.areRoughlyEqual(string.getVector("-1.234", nil)[1], -1.234)
	Assert.areRoughlyEqual(string.getVector("-1.234", 1)[1], -1.234)
	Assert.areEqual(#string.getVector("1 2 3 4 5 6 7 8 9 10"), 10)
	Assert.areEqual(#string.getVector("1 2 3 4 5 6 7 8 9 10", nil), 10)
	Assert.areEqual(#string.getVector("1 2 3 4 5 6 7 8 9 10", 10), 10)
end
function StringTest.test_startsWith()
	Assert.isTrue(string.startsWith("", ""))
	Assert.isTrue(string.startsWith("a", ""))
	Assert.isTrue(string.startsWith(" ", ""))
	Assert.isTrue(string.startsWith("a", "a"))
	Assert.isTrue(string.startsWith("ab", "a"))
	Assert.isFalse(string.startsWith("", "a"))
	Assert.isFalse(string.startsWith("", " "))
	Assert.isFalse(string.startsWith("a", "A"))
	Assert.isFalse(string.startsWith("A", "a"))
	local str, firstChar, lastChar = StringTest.generateRandomStr(100000)
	Assert.isTrue(string.startsWith(str, firstChar))
	Assert.isFalse(string.startsWith(str, lastChar))
	Assert.throwsError(function()
		local str = nil
		string.startsWith(nil, "")
	end, "Nil value for string does not raise an error")
	Assert.throwsError(function()
		local prefix = nil
		string.startsWith("", nil)
	end, "Nil value for prefix does not raise an error")
	Assert.throwsError(function()
		local prefix = {}
		string.startsWith("", prefix)
	end, "table value for prefix does not raise an error")
	Assert.throwsError(function()
		local prefix = true
		string.startsWith("1", true)
	end, "boolean value for prefix does not raise an error")
end
function StringTest.test_endsWith()
	Assert.isTrue(string.endsWith("", ""))
	Assert.isTrue(string.endsWith("a", ""))
	Assert.isTrue(string.endsWith(" ", ""))
	Assert.isTrue(string.endsWith("a", "a"))
	Assert.isTrue(string.endsWith("ab", "b"))
	Assert.isFalse(string.endsWith("", "a"))
	Assert.isFalse(string.endsWith("", " "))
	Assert.isFalse(string.endsWith("a", "A"))
	Assert.isFalse(string.endsWith("A", "a"))
	local str, firstChar, lastChar = StringTest.generateRandomStr(100000)
	Assert.isTrue(string.endsWith(str, lastChar))
	Assert.isFalse(string.endsWith(str, firstChar))
	Assert.throwsError(function()
		local str = nil
		string.endsWith(nil, "")
	end, "Nil value for string does not raise an error")
	Assert.throwsError(function()
		local suffix = nil
		string.endsWith("", nil)
	end, "Nil value for suffix does not raise an error")
	Assert.throwsError(function()
		local suffix = {}
		string.endsWith("", suffix)
	end, "table value for suffix does not raise an error")
	Assert.throwsError(function()
		local suffix = true
		string.endsWith("1", true)
	end, "boolean value for suffix does not raise an error")
end
function StringTest.test_trim()
	Assert.throwsError(function()
		local str = nil
		string.trim(nil)
	end, "Nil value for string does not raise an error")
	Assert.areEqual(string.trim(""), "")
	Assert.areEqual(string.trim(" "), "")
	Assert.areEqual(string.trim("\n"), "")
	Assert.areEqual(string.trim("\r"), "")
	Assert.areEqual(string.trim("\n\r"), "")
	Assert.areEqual(string.trim("\r\n"), "")
	Assert.areEqual(string.trim(" \n"), "")
	Assert.areEqual(string.trim(" \r"), "")
	Assert.areEqual(string.trim(" \n\r"), "")
	Assert.areEqual(string.trim(" \r\n"), "")
	Assert.areEqual(string.trim("\n "), "")
	Assert.areEqual(string.trim("\r "), "")
	Assert.areEqual(string.trim("\n\r "), "")
	Assert.areEqual(string.trim("\r\n "), "")
	Assert.areEqual(string.trim("abc"), "abc")
	Assert.areEqual(string.trim(" abc"), "abc")
	Assert.areEqual(string.trim("abc "), "abc")
	Assert.areEqual(string.trim(" abc "), "abc")
	Assert.areEqual(string.trim("\195\164 "), "\195\164")
	Assert.areEqual(string.trim(" \195\164 "), "\195\164")
	Assert.areEqual(string.trim(" \195\164 \195\188 "), "\195\164 \195\188")
	Assert.areEqual(string.trim(" ab c "), "ab c")
	Assert.areEqual(string.trim("\tabc\t"), "abc")
	Assert.areEqual(string.trim("\nabc\n"), "abc")
	Assert.areEqual(string.trim(" \nabc \n"), "abc")
	Assert.areEqual(string.trim("\n abc\n "), "abc")
	Assert.areEqual(string.trim("\rabc\r"), "abc")
	Assert.areEqual(string.trim(" \rabc \r"), "abc")
	Assert.areEqual(string.trim("\r abc\r "), "abc")
	Assert.areEqual(string.trim("\n\rabc\n\r"), "abc")
	Assert.areEqual(string.trim("\r\nabc\r\n"), "abc")
end
function StringTest.test_ltrim()
	Assert.throwsError(function()
		local str = nil
		string.ltrim(nil)
	end, "Nil value for string does not raise an error")
	Assert.areEqual(string.ltrim(""), "")
	Assert.areEqual(string.ltrim(" "), "")
	Assert.areEqual(string.ltrim("\n"), "")
	Assert.areEqual(string.ltrim("\r"), "")
	Assert.areEqual(string.ltrim("\n\r"), "")
	Assert.areEqual(string.ltrim("\r\n"), "")
	Assert.areEqual(string.ltrim(" \n"), "")
	Assert.areEqual(string.ltrim(" \r"), "")
	Assert.areEqual(string.ltrim(" \n\r"), "")
	Assert.areEqual(string.ltrim(" \r\n"), "")
	Assert.areEqual(string.ltrim("\n "), "")
	Assert.areEqual(string.ltrim("\r "), "")
	Assert.areEqual(string.ltrim("\n\r "), "")
	Assert.areEqual(string.ltrim("\r\n "), "")
	Assert.areEqual(string.ltrim("abc"), "abc")
	Assert.areEqual(string.ltrim(" abc"), "abc")
	Assert.areEqual(string.ltrim("abc "), "abc ")
	Assert.areEqual(string.ltrim(" abc "), "abc ")
	Assert.areEqual(string.ltrim("\195\164 "), "\195\164 ")
	Assert.areEqual(string.ltrim(" \195\164 "), "\195\164 ")
	Assert.areEqual(string.ltrim(" \195\164 \195\188 "), "\195\164 \195\188 ")
	Assert.areEqual(string.ltrim(" ab c "), "ab c ")
	Assert.areEqual(string.ltrim("\tabc\t"), "abc\t")
	Assert.areEqual(string.ltrim("\nabc\n"), "abc\n")
	Assert.areEqual(string.ltrim(" \nabc \n"), "abc \n")
	Assert.areEqual(string.ltrim("\n abc\n "), "abc\n ")
	Assert.areEqual(string.ltrim("\rabc\r"), "abc\r")
	Assert.areEqual(string.ltrim(" \rabc \r"), "abc \r")
	Assert.areEqual(string.ltrim("\r abc\r "), "abc\r ")
	Assert.areEqual(string.ltrim("\n\rabc\n\r"), "abc\n\r")
	Assert.areEqual(string.ltrim("\r\nabc\r\n"), "abc\r\n")
end
function StringTest.test_rtrim()
	Assert.throwsError(function()
		local str = nil
		string.rtrim(nil)
	end, "Nil value for string does not raise an error")
	Assert.areEqual(string.rtrim(""), "")
	Assert.areEqual(string.rtrim(" "), "")
	Assert.areEqual(string.rtrim("\n"), "")
	Assert.areEqual(string.rtrim("\r"), "")
	Assert.areEqual(string.rtrim("\n\r"), "")
	Assert.areEqual(string.rtrim("\r\n"), "")
	Assert.areEqual(string.rtrim(" \n"), "")
	Assert.areEqual(string.rtrim(" \r"), "")
	Assert.areEqual(string.rtrim(" \n\r"), "")
	Assert.areEqual(string.rtrim(" \r\n"), "")
	Assert.areEqual(string.rtrim("\n "), "")
	Assert.areEqual(string.rtrim("\r "), "")
	Assert.areEqual(string.rtrim("\n\r "), "")
	Assert.areEqual(string.rtrim("\r\n "), "")
	Assert.areEqual(string.rtrim("abc"), "abc")
	Assert.areEqual(string.rtrim(" abc"), " abc")
	Assert.areEqual(string.rtrim("abc "), "abc")
	Assert.areEqual(string.rtrim(" abc "), " abc")
	Assert.areEqual(string.rtrim("\195\164 "), "\195\164")
	Assert.areEqual(string.rtrim(" \195\164 "), " \195\164")
	Assert.areEqual(string.rtrim(" \195\164 \195\188 "), " \195\164 \195\188")
	Assert.areEqual(string.rtrim(" ab c "), " ab c")
	Assert.areEqual(string.rtrim("\tabc\t"), "\tabc")
	Assert.areEqual(string.rtrim("\nabc\n"), "\nabc")
	Assert.areEqual(string.rtrim(" \nabc \n"), " \nabc")
	Assert.areEqual(string.rtrim("\n abc\n "), "\n abc")
	Assert.areEqual(string.rtrim("\rabc\r"), "\rabc")
	Assert.areEqual(string.rtrim(" \rabc \r"), " \rabc")
	Assert.areEqual(string.rtrim("\r abc\r "), "\r abc")
	Assert.areEqual(string.rtrim("\n\rabc\n\r"), "\n\rabc")
	Assert.areEqual(string.rtrim("\r\nabc\r\n"), "\r\nabc")
end
function StringTest.test_findLast()
	Assert.throwsError(function()
		local str = nil
		string.findLast(nil, "a")
	end, "Nil value for string does not raise an error")
	Assert.throwsError(function()
		local str = "a"
		local substr = nil
		string.findLast("a", nil)
	end, "Nil value for substring does not raise an error")
	Assert.areEqual(string.findLast("", ""), 1)
	Assert.areEqual(string.findLast("", "d"), 0)
	Assert.areEqual(string.findLast("abc", "d"), 0)
	Assert.areEqual(string.findLast("abc", "c"), 3)
	Assert.areEqual(string.findLast("abc", "a"), 1)
	Assert.areEqual(string.findLast("abc", "abc"), 1)
	Assert.areEqual(string.findLast("abac", "a"), 3)
	Assert.areEqual(string.findLast("abcabc", "bc"), 5)
	local str = "abc"
	Assert.areEqual(string.findLast("abc", ""), 4)
	Assert.areEqual(string.findLast("abc", ".c"), 2)
	Assert.areEqual(string.findLast("abc", "b.c"), 0)
	Assert.areEqual(string.findLast("abc", ".c", true), 0)
	Assert.areEqual(string.findLast("abc", "bc", true), 2)
	Assert.throwsError(function()
		string.findLast("abc", "bc", 10)
	end, "Number value for 'plain' argument does not raise an error")
	Assert.throwsError(function()
		string.findLast("abc", "bc", {})
	end, "Table value for 'plain' argument does not raise an error")
	Assert.throwsError(function()
		string.findLast("abc", "bc", "yes")
	end, "String value for 'plain' argument does not raise an error")
end
function StringTest.generateRandomStr(length)
	local str = nil
	local chars = table.create(length)
	local lastChar = nil
	local firstChar = nil
	for i = 1, length do
		local char = string.char(math.random(0, 255))
		chars[#chars + 1] = char
		if #chars == 1 then
			firstChar = char
		elseif #chars == length then
			lastChar = char
		end
	end
	str = table.concat(chars)
	local randomIndex = math.random(1, length)
	local randomChar = string.sub(str, randomIndex, randomIndex)
	return str, firstChar, lastChar, randomChar
end
local standardLuaFunctions = { ["unpack"] = true, ["match"] = true, ["gmatch"] = true, ["upper"] = true, ["gsub"] = true, ["format"] = true, ["lower"] = true, ["sub"] = true, ["pack"] = true, ["find"] = true, ["char"] = true, ["dump"] = true, ["packsize"] = true, ["reverse"] = true, ["byte"] = true, ["rep"] = true, ["len"] = true }
for k in pairs(string) do
	if StringTest["test_" .. k] == nil and standardLuaFunctions[k] == nil then
		printWarning("Warning: no test function for function string." .. k)
	end
end
