XMLTest = {}
function XMLTest.getTestXML()
	return loadXMLFileFromMemory("testXML", "        <test integer=\'3\' integerNeg=\'-4\' uinteger=\'4294967295\' boolean=\'true\' float=\'5.6\' empty=\'\'>\n            <integer>4</integer>\n            <integerNeg>-4</integerNeg>\n            <uinteger>4294967295</uinteger>\n            <boolean>false</boolean>\n            <float>6.6</float>\n            <empty></empty>\n\n            <integerExcess>4a</integerExcess>\n            <booleanExcess>false </booleanExcess>\n            <floatExcess>6.6a</floatExcess>\n\n            <attributeTestZero>\n                <child attr=\"\"/>\n            </attributeTestZero>\n            <attributeTestOne one=\"true\" />\n            <attributeTestTwo one=\"true\" two=\"false\" />\n        </test>\n    ")
end
function XMLTest.test_loadXMLFileFromMemory()
	Assert.areEqual(loadXMLFileFromMemory("test_loadXMLFileFromMemory", ""), 0)
	Assert.areEqual(loadXMLFileFromMemory("test_loadXMLFileFromMemory", "test"), 0)
	Assert.areEqual(loadXMLFileFromMemory("test_loadXMLFileFromMemory", "<test>"), 0)
	local v1_ = loadXMLFileFromMemory("test_loadXMLFileFromMemory", "<!-- -->")
	Assert.areNotEqual(v1_, 0)
	delete(v1_)
	local v2_ = loadXMLFileFromMemory("test_loadXMLFileFromMemory", "<test/>")
	Assert.areNotEqual(v2_, 0)
	delete(v2_)
	local v3_ = loadXMLFileFromMemory("test_loadXMLFileFromMemory", "<test attr=\"\" attr2=\"2\"/>")
	Assert.areNotEqual(v3_, 0)
	delete(v3_)
end
function XMLTest.test_getXMLBool()
	local v4_ = XMLTest.getTestXML()
	Assert.areEqual(getXMLBool(v4_, "test#boolean"), true)
	Assert.areEqual(getXMLBool(v4_, "test.boolean"), false)
	Assert.areEqual(getXMLBool(v4_, "test#nonExisting"), nil)
	Assert.areEqual(getXMLBool(v4_, "test.nonExisting"), nil)
	Assert.areEqual(getXMLBool(v4_, "test#integer"), nil)
	Assert.areEqual(getXMLBool(v4_, "test.integer"), nil)
	Assert.areEqual(getXMLBool(v4_, "test#float"), nil)
	Assert.areEqual(getXMLBool(v4_, "test.float"), nil)
	Assert.areEqual(getXMLBool(v4_, "test#empty"), nil)
	Assert.areEqual(getXMLBool(v4_, "test.empty"), nil)
	delete(v4_)
end
function XMLTest.test_getXMLFloat()
	local v5_ = XMLTest.getTestXML()
	Assert.areRoughlyEqual(getXMLFloat(v5_, "test#float"), 5.6)
	Assert.areRoughlyEqual(getXMLFloat(v5_, "test.float"), 6.6)
	Assert.areEqual(getXMLFloat(v5_, "test#nonExisting"), nil)
	Assert.areEqual(getXMLFloat(v5_, "test.nonExisting"), nil)
	Assert.areEqual(getXMLFloat(v5_, "test#boolean"), nil)
	Assert.areEqual(getXMLFloat(v5_, "test.boolean"), nil)
	Assert.areEqual(getXMLFloat(v5_, "test#integer"), 3)
	Assert.areEqual(getXMLFloat(v5_, "test.integer"), 4)
	Assert.areEqual(getXMLFloat(v5_, "test#empty"), nil)
	Assert.areEqual(getXMLFloat(v5_, "test.empty"), nil)
	delete(v5_)
end
function XMLTest.test_getXMLInt()
	local v6_ = XMLTest.getTestXML()
	Assert.areEqual(getXMLInt(v6_, "test#integer"), 3)
	Assert.areEqual(getXMLInt(v6_, "test.integer"), 4)
	Assert.areEqual(getXMLInt(v6_, "test#nonExisting"), nil)
	Assert.areEqual(getXMLInt(v6_, "test.nonExisting"), nil)
	Assert.areEqual(getXMLInt(v6_, "test#float"), 5)
	Assert.areEqual(getXMLInt(v6_, "test.float"), 6)
	Assert.areEqual(getXMLInt(v6_, "test#boolean"), nil)
	Assert.areEqual(getXMLInt(v6_, "test.boolean"), nil)
	Assert.areEqual(getXMLInt(v6_, "test#empty"), nil)
	Assert.areEqual(getXMLInt(v6_, "test.empty"), nil)
	delete(v6_)
end
function XMLTest.test_getXMLUInt()
	local v7_ = XMLTest.getTestXML()
	Assert.areEqual(getXMLUInt(v7_, "test#integer"), 3)
	Assert.areEqual(getXMLUInt(v7_, "test.integer"), 4)
	Assert.areEqual(getXMLUInt(v7_, "test#uinteger"), 4294967295)
	Assert.areEqual(getXMLUInt(v7_, "test.uinteger"), 4294967295)
	Assert.areEqual(getXMLUInt(v7_, "test#integerNeg"), nil, "getXMLUInt should return nil for negative value in xml attribute")
	Assert.areEqual(getXMLUInt(v7_, "test.integerNeg"), nil, "getXMLUInt should return nil for negative value in xml element")
	Assert.areEqual(getXMLUInt(v7_, "test#nonExisting"), nil)
	Assert.areEqual(getXMLUInt(v7_, "test.nonExisting"), nil)
	Assert.areEqual(getXMLUInt(v7_, "test#float"), 5)
	Assert.areEqual(getXMLUInt(v7_, "test.float"), 6)
	Assert.areEqual(getXMLUInt(v7_, "test#boolean"), nil, "getXMLUInt should return nil for boolean/string value in xml attribute")
	Assert.areEqual(getXMLUInt(v7_, "test.boolean"), nil, "getXMLUInt should return nil for boolean/string value in xml element")
	Assert.areEqual(getXMLUInt(v7_, "test#empty"), nil)
	Assert.areEqual(getXMLUInt(v7_, "test.empty"), nil)
	delete(v7_)
end
function XMLTest.test_setXMLInt()
	local v8_ = createXMLFile("XMLTest", "", "test")
	setXMLInt(v8_, "test.int", 2147483647)
	Assert.areEqual(getXMLString(v8_, "test.int"), (tostring(2147483647)))
	setXMLInt(v8_, "test.int", -2147483648)
	Assert.areEqual(getXMLString(v8_, "test.int"), (tostring(-2147483648)))
	setXMLInt(v8_, "test.int", 1.8)
	Assert.areEqual(getXMLString(v8_, "test.int"), (tostring(2)))
	setXMLInt(v8_, "test.int", -1.8)
	Assert.areEqual(getXMLString(v8_, "test.int"), (tostring(-2)))
	setXMLInt(v8_, "test.int", -1.45)
	Assert.areEqual(getXMLString(v8_, "test.int"), (tostring(-1)))
	delete(v8_)
end
function XMLTest.test_setXMLUInt()
	local v9_ = createXMLFile("XMLTest", "", "test")
	setXMLUInt(v9_, "test.uint", 4294967295)
	Assert.areEqual(getXMLString(v9_, "test.uint"), (tostring(4294967295)))
	setXMLUInt(v9_, "test.uint", 1.8)
	Assert.areEqual(getXMLString(v9_, "test.uint"), (tostring(2)))
	setXMLUInt(v9_, "test.uint", 1.45)
	Assert.areEqual(getXMLString(v9_, "test.uint"), (tostring(1)))
	delete(v9_)
end
function XMLTest.test_getXMLNumOfAttributes()
	local v10_ = XMLTest.getTestXML()
	Assert.areEqual(getXMLNumOfAttributes(v10_, "test.attributeTestZero"), 0)
	Assert.areEqual(getXMLNumOfAttributes(v10_, "test.attributeTestOne"), 1)
	Assert.areEqual(getXMLNumOfAttributes(v10_, "test.attributeTestTwo"), 2)
	delete(v10_)
end
function XMLTest.test_getXMLAttributeName()
	local v11_ = XMLTest.getTestXML()
	Assert.isNil(getXMLAttributeName(v11_, "test.attributeTestZero", 0))
	Assert.areEqual(getXMLAttributeName(v11_, "test.attributeTestOne", 0), "one")
	Assert.isNil(getXMLAttributeName(v11_, "test.attributeTestOne", 1))
	Assert.areEqual(getXMLAttributeName(v11_, "test.attributeTestTwo", 0), "one")
	Assert.areEqual(getXMLAttributeName(v11_, "test.attributeTestTwo", 1), "two")
	Assert.isNil(getXMLAttributeName(v11_, "test.attributeTestTwo", 2))
	delete(v11_)
end
function XMLTest.test_getXMLLineNum()
	local v12_ = XMLTest.getTestXML()
	Assert.areEqual(getXMLLineNum(v12_, "test"), 1)
	Assert.areEqual(getXMLLineNum(v12_, "test#integer"), 1)
	Assert.areEqual(getXMLLineNum(v12_, "test.integer"), 2)
	Assert.areEqual(getXMLLineNum(v12_, "test.attributeTestOne"), 16)
	Assert.areEqual(getXMLLineNum(v12_, "test.attributeTestOne#one"), 16)
	Assert.areEqual(getXMLLineNum(v12_, "test.nonExistentElement"), 0)
	Assert.areEqual(getXMLLineNum(v12_, "test.attributeTestOne#noneExistentAttribute"), 0)
	Assert.areEqual(getXMLLineNum(v12_, ""), 0)
	Assert.areEqual(getXMLLineNum(v12_, "."), 0)
	delete(v12_)
end
