XMLTest = {}
function XMLTest.getTestXML()
	local xmlStr = "        <test integer='3' integerNeg='-4' uinteger='4294967295' boolean='true' float='5.6' empty=''>\n            <integer>4</integer>\n            <integerNeg>-4</integerNeg>\n            <uinteger>4294967295</uinteger>\n            <boolean>false</boolean>\n            <float>6.6</float>\n            <empty></empty>\n\n            <integerExcess>4a</integerExcess>\n            <booleanExcess>false </booleanExcess>\n            <floatExcess>6.6a</floatExcess>\n\n            <attributeTestZero>\n                <child attr=\"\"/>\n            </attributeTestZero>\n            <attributeTestOne one=\"true\" />\n            <attributeTestTwo one=\"true\" two=\"false\" />\n        </test>\n    "
	return loadXMLFileFromMemory("testXML", "        <test integer='3' integerNeg='-4' uinteger='4294967295' boolean='true' float='5.6' empty=''>\n            <integer>4</integer>\n            <integerNeg>-4</integerNeg>\n            <uinteger>4294967295</uinteger>\n            <boolean>false</boolean>\n            <float>6.6</float>\n            <empty></empty>\n\n            <integerExcess>4a</integerExcess>\n            <booleanExcess>false </booleanExcess>\n            <floatExcess>6.6a</floatExcess>\n\n            <attributeTestZero>\n                <child attr=\"\"/>\n            </attributeTestZero>\n            <attributeTestOne one=\"true\" />\n            <attributeTestTwo one=\"true\" two=\"false\" />\n        </test>\n    ")
end
function XMLTest.test_loadXMLFileFromMemory()
	Assert.areEqual(loadXMLFileFromMemory("test_loadXMLFileFromMemory", ""), 0)
	Assert.areEqual(loadXMLFileFromMemory("test_loadXMLFileFromMemory", "test"), 0)
	Assert.areEqual(loadXMLFileFromMemory("test_loadXMLFileFromMemory", "<test>"), 0)
	local testXML = loadXMLFileFromMemory("test_loadXMLFileFromMemory", "<!-- -->")
	Assert.areNotEqual(testXML, 0)
	delete(testXML)
	testXML = loadXMLFileFromMemory("test_loadXMLFileFromMemory", "<test/>")
	Assert.areNotEqual(testXML, 0)
	delete(testXML)
	testXML = loadXMLFileFromMemory("test_loadXMLFileFromMemory", '<test attr="" attr2="2"/>')
	Assert.areNotEqual(testXML, 0)
	delete(testXML)
end
function XMLTest.test_getXMLBool()
	local xml = XMLTest.getTestXML()
	Assert.areEqual(getXMLBool(xml, "test#boolean"), true)
	Assert.areEqual(getXMLBool(xml, "test.boolean"), false)
	Assert.areEqual(getXMLBool(xml, "test#nonExisting"), nil)
	Assert.areEqual(getXMLBool(xml, "test.nonExisting"), nil)
	Assert.areEqual(getXMLBool(xml, "test#integer"), nil)
	Assert.areEqual(getXMLBool(xml, "test.integer"), nil)
	Assert.areEqual(getXMLBool(xml, "test#float"), nil)
	Assert.areEqual(getXMLBool(xml, "test.float"), nil)
	Assert.areEqual(getXMLBool(xml, "test#empty"), nil)
	Assert.areEqual(getXMLBool(xml, "test.empty"), nil)
	delete(xml)
end
function XMLTest.test_getXMLFloat()
	local xml = XMLTest.getTestXML()
	Assert.areRoughlyEqual(getXMLFloat(xml, "test#float"), 5.6)
	Assert.areRoughlyEqual(getXMLFloat(xml, "test.float"), 6.6)
	Assert.areEqual(getXMLFloat(xml, "test#nonExisting"), nil)
	Assert.areEqual(getXMLFloat(xml, "test.nonExisting"), nil)
	Assert.areEqual(getXMLFloat(xml, "test#boolean"), nil)
	Assert.areEqual(getXMLFloat(xml, "test.boolean"), nil)
	Assert.areEqual(getXMLFloat(xml, "test#integer"), 3)
	Assert.areEqual(getXMLFloat(xml, "test.integer"), 4)
	Assert.areEqual(getXMLFloat(xml, "test#empty"), nil)
	Assert.areEqual(getXMLFloat(xml, "test.empty"), nil)
	delete(xml)
end
function XMLTest.test_getXMLInt()
	local xml = XMLTest.getTestXML()
	Assert.areEqual(getXMLInt(xml, "test#integer"), 3)
	Assert.areEqual(getXMLInt(xml, "test.integer"), 4)
	Assert.areEqual(getXMLInt(xml, "test#nonExisting"), nil)
	Assert.areEqual(getXMLInt(xml, "test.nonExisting"), nil)
	Assert.areEqual(getXMLInt(xml, "test#float"), 5)
	Assert.areEqual(getXMLInt(xml, "test.float"), 6)
	Assert.areEqual(getXMLInt(xml, "test#boolean"), nil)
	Assert.areEqual(getXMLInt(xml, "test.boolean"), nil)
	Assert.areEqual(getXMLInt(xml, "test#empty"), nil)
	Assert.areEqual(getXMLInt(xml, "test.empty"), nil)
	delete(xml)
end
function XMLTest.test_getXMLUInt()
	local xml = XMLTest.getTestXML()
	Assert.areEqual(getXMLUInt(xml, "test#integer"), 3)
	Assert.areEqual(getXMLUInt(xml, "test.integer"), 4)
	Assert.areEqual(getXMLUInt(xml, "test#uinteger"), 4294967295)
	Assert.areEqual(getXMLUInt(xml, "test.uinteger"), 4294967295)
	Assert.areEqual(getXMLUInt(xml, "test#integerNeg"), nil, "getXMLUInt should return nil for negative value in xml attribute")
	Assert.areEqual(getXMLUInt(xml, "test.integerNeg"), nil, "getXMLUInt should return nil for negative value in xml element")
	Assert.areEqual(getXMLUInt(xml, "test#nonExisting"), nil)
	Assert.areEqual(getXMLUInt(xml, "test.nonExisting"), nil)
	Assert.areEqual(getXMLUInt(xml, "test#float"), 5)
	Assert.areEqual(getXMLUInt(xml, "test.float"), 6)
	Assert.areEqual(getXMLUInt(xml, "test#boolean"), nil, "getXMLUInt should return nil for boolean/string value in xml attribute")
	Assert.areEqual(getXMLUInt(xml, "test.boolean"), nil, "getXMLUInt should return nil for boolean/string value in xml element")
	Assert.areEqual(getXMLUInt(xml, "test#empty"), nil)
	Assert.areEqual(getXMLUInt(xml, "test.empty"), nil)
	delete(xml)
end
function XMLTest.test_setXMLInt()
	local xml = createXMLFile("XMLTest", "", "test")
	local intMaxVal = 2147483647
	setXMLInt(xml, "test.int", 2147483647)
	Assert.areEqual(getXMLString(xml, "test.int"), tostring(intMaxVal))
	local intMinVal = -2147483648
	setXMLInt(xml, "test.int", -2147483648)
	Assert.areEqual(getXMLString(xml, "test.int"), tostring(intMinVal))
	local floatVal = 1.8
	local roundedIntVal = 2
	setXMLInt(xml, "test.int", floatVal)
	Assert.areEqual(getXMLString(xml, "test.int"), tostring(roundedIntVal))
	floatVal = -1.8
	roundedIntVal = -2
	setXMLInt(xml, "test.int", floatVal)
	Assert.areEqual(getXMLString(xml, "test.int"), tostring(roundedIntVal))
	floatVal = -1.45
	roundedIntVal = -1
	setXMLInt(xml, "test.int", floatVal)
	Assert.areEqual(getXMLString(xml, "test.int"), tostring(roundedIntVal))
	delete(xml)
end
function XMLTest.test_setXMLUInt()
	local xml = createXMLFile("XMLTest", "", "test")
	local uintMaxVal = 4294967295
	setXMLUInt(xml, "test.uint", 4294967295)
	Assert.areEqual(getXMLString(xml, "test.uint"), tostring(uintMaxVal))
	local floatVal = 1.8
	local roundedIntVal = 2
	setXMLUInt(xml, "test.uint", floatVal)
	Assert.areEqual(getXMLString(xml, "test.uint"), tostring(roundedIntVal))
	floatVal = 1.45
	roundedIntVal = 1
	setXMLUInt(xml, "test.uint", floatVal)
	Assert.areEqual(getXMLString(xml, "test.uint"), tostring(roundedIntVal))
	delete(xml)
end
function XMLTest.test_getXMLNumOfAttributes()
	local xml = XMLTest.getTestXML()
	Assert.areEqual(getXMLNumOfAttributes(xml, "test.attributeTestZero"), 0)
	Assert.areEqual(getXMLNumOfAttributes(xml, "test.attributeTestOne"), 1)
	Assert.areEqual(getXMLNumOfAttributes(xml, "test.attributeTestTwo"), 2)
	delete(xml)
end
function XMLTest.test_getXMLAttributeName()
	local xml = XMLTest.getTestXML()
	Assert.isNil(getXMLAttributeName(xml, "test.attributeTestZero", 0))
	Assert.areEqual(getXMLAttributeName(xml, "test.attributeTestOne", 0), "one")
	Assert.isNil(getXMLAttributeName(xml, "test.attributeTestOne", 1))
	Assert.areEqual(getXMLAttributeName(xml, "test.attributeTestTwo", 0), "one")
	Assert.areEqual(getXMLAttributeName(xml, "test.attributeTestTwo", 1), "two")
	Assert.isNil(getXMLAttributeName(xml, "test.attributeTestTwo", 2))
	delete(xml)
end
function XMLTest.test_getXMLLineNum()
	local xml = XMLTest.getTestXML()
	Assert.areEqual(getXMLLineNum(xml, "test"), 1)
	Assert.areEqual(getXMLLineNum(xml, "test#integer"), 1)
	Assert.areEqual(getXMLLineNum(xml, "test.integer"), 2)
	Assert.areEqual(getXMLLineNum(xml, "test.attributeTestOne"), 16)
	Assert.areEqual(getXMLLineNum(xml, "test.attributeTestOne#one"), 16)
	Assert.areEqual(getXMLLineNum(xml, "test.nonExistentElement"), 0)
	Assert.areEqual(getXMLLineNum(xml, "test.attributeTestOne#noneExistentAttribute"), 0)
	Assert.areEqual(getXMLLineNum(xml, ""), 0)
	Assert.areEqual(getXMLLineNum(xml, "."), 0)
	delete(xml)
end
