local messageTypeId = 0
function nextMessageTypeId()
	messageTypeId = messageTypeId + 1
	return messageTypeId
end
MessageType = {}
function MessageType.getMessageNameById(messageTypeId)
	if type(messageTypeId) == "number" then
		for messageName, typeId in pairs(MessageType) do
			if messageTypeId == typeId then
				return messageName
			end
		end
		for messageName, typeId in pairs(MessageType.SETTING_CHANGED) do
			if messageTypeId == typeId then
				return "SETTING_CHANGED:" .. messageName
			end
		end
		return string.format("<unknownMessageType '%d'>", messageTypeId)
	else
		return ClassUtil.getClassName(messageTypeId) or string.format("<unknownMessageType '%s'>", messageTypeId)
	end
end
MessageType.MONEY_CHANGED = nextMessageTypeId()
MessageType.PLAYER_FARM_CHANGED = nextMessageTypeId()
MessageType.FARM_CREATED = nextMessageTypeId()
MessageType.FARM_SETTINGS_CHANGED = nextMessageTypeId()
MessageType.FARM_DELETED = nextMessageTypeId()
MessageType.FARM_PROPERTY_CHANGED = nextMessageTypeId()
MessageType.FARMLAND_OWNER_CHANGED = nextMessageTypeId()
MessageType.PLACEABLE_ADDED = nextMessageTypeId()
MessageType.PLACEABLE_REMOVED = nextMessageTypeId()
MessageType.PLAYER_CREATED = nextMessageTypeId()
MessageType.PLAYER_NICKNAME_CHANGED = nextMessageTypeId()
MessageType.OWN_PLAYER_ENTERED = nextMessageTypeId()
MessageType.OWN_PLAYER_LEFT = nextMessageTypeId()
MessageType.PLAYER_PRE_TELEPORT = nextMessageTypeId()
MessageType.ACHIEVEMENT_UNLOCKED = nextMessageTypeId()
MessageType.PAUSE = nextMessageTypeId()
MessageType.HUSBANDRY_ANIMALS_CHANGED = nextMessageTypeId()
MessageType.VEHICLE_REPAIRED = nextMessageTypeId()
MessageType.VEHICLE_REPAINTED = nextMessageTypeId()
MessageType.VEHICLE_RESET = nextMessageTypeId()
MessageType.VEHICLE_LOADED = nextMessageTypeId()
MessageType.HANDTOOL_LOADED = nextMessageTypeId()
MessageType.VEHICLE_ADDED = nextMessageTypeId()
MessageType.HANDTOOL_ADDED = nextMessageTypeId()
MessageType.VEHICLE_REMOVED = nextMessageTypeId()
MessageType.HANDTOOL_REMOVED = nextMessageTypeId()
MessageType.VEHICLE_SALES_CHANGED = nextMessageTypeId()
MessageType.VEHICLE_PLAYER_ENTERED = nextMessageTypeId()
MessageType.VEHICLE_PLAYER_LEFT = nextMessageTypeId()
MessageType.STORE_ITEMS_RELOADED = nextMessageTypeId()
MessageType.GUI_BEFORE_OPEN = nextMessageTypeId()
MessageType.GUI_AFTER_OPEN = nextMessageTypeId()
MessageType.GUI_BEFORE_CLOSE = nextMessageTypeId()
MessageType.GUI_AFTER_CLOSE = nextMessageTypeId()
MessageType.GUI_INGAME_OPEN = nextMessageTypeId()
MessageType.GUI_INGAME_OPEN_FINANCES_SCREEN = nextMessageTypeId()
MessageType.GUI_INGAME_OPEN_FARMS_SCREEN = nextMessageTypeId()
MessageType.GUI_INGAME_OPEN_PRODUCTION_SCREEN = nextMessageTypeId()
MessageType.GUI_INGAME_OPEN_AI_SCREEN = nextMessageTypeId()
MessageType.GUI_INGAME_OPEN_HELP_SCREEN = nextMessageTypeId()
MessageType.GUI_MAIN_SCREEN_OPEN = nextMessageTypeId()
MessageType.GUI_DIALOG_OPENED = nextMessageTypeId()
MessageType.SAVEGAMES_LOADED = nextMessageTypeId()
MessageType.GAME_STATE_CHANGED = nextMessageTypeId()
MessageType.CURRENT_MISSION_START = nextMessageTypeId()
MessageType.CURRENT_MISSION_LOADED = nextMessageTypeId()
MessageType.SETTING_CHANGED = {}
if GameSettings ~= nil then
	for _, setting in pairs(GameSettings.SETTING) do
		MessageType.SETTING_CHANGED[setting] = nextMessageTypeId()
	end
end
MessageType.INPUT_BINDINGS_CHANGED = nextMessageTypeId()
MessageType.INPUT_MODE_CHANGED = nextMessageTypeId()
MessageType.INPUT_HELP_MODE_CHANGED = nextMessageTypeId()
MessageType.INPUT_DEVICES_CHANGED = nextMessageTypeId()
MessageType.TIMESCALE_CHANGED = nextMessageTypeId()
MessageType.SAVEGAME_LOADED = nextMessageTypeId()
MessageType.MISSION_GENERATED = nextMessageTypeId()
MessageType.MISSION_DELETED = nextMessageTypeId()
MessageType.MISSION_GENERATION_START = nextMessageTypeId()
MessageType.MISSION_GENERATION_END = nextMessageTypeId()
MessageType.MISSION_STATUS_CHANGED = nextMessageTypeId()
MessageType.GUIDED_TOUR_STARTED = nextMessageTypeId()
MessageType.GUIDED_TOUR_FINISHED = nextMessageTypeId()
MessageType.GUIDED_TOUR_CHANGED = nextMessageTypeId()
MessageType.GUIDED_TOUR_DIALOG = nextMessageTypeId()
MessageType.USER_PROFILE_CHANGED = nextMessageTypeId()
MessageType.BLOCK_LIST_CHANGED = nextMessageTypeId()
MessageType.USER_ADDED = nextMessageTypeId()
MessageType.USER_REMOVED = nextMessageTypeId()
MessageType.MASTERUSER_ADDED = nextMessageTypeId()
MessageType.PLAYER_STYLE_CHANGED = nextMessageTypeId()
MessageType.MINUTE_CHANGED = nextMessageTypeId()
MessageType.HOUR_CHANGED = nextMessageTypeId()
MessageType.DAY_CHANGED = nextMessageTypeId()
MessageType.REALHOUR_CHANGED = nextMessageTypeId()
MessageType.PERIOD_CHANGED = nextMessageTypeId()
MessageType.PERIOD_LENGTH_CHANGED = nextMessageTypeId()
MessageType.SEASON_CHANGED = nextMessageTypeId()
MessageType.YEAR_CHANGED = nextMessageTypeId()
MessageType.DAYLIGHT_CHANGED = nextMessageTypeId()
MessageType.WEATHER_CHANGED = nextMessageTypeId()
MessageType.DAY_NIGHT_CHANGED = nextMessageTypeId()
MessageType.SNOW_HEIGHT_CHANGED = nextMessageTypeId()
MessageType.UNLOADING_STATIONS_CHANGED = nextMessageTypeId()
MessageType.LOADING_STATIONS_CHANGED = nextMessageTypeId()
MessageType.AI_VEHICLE_STATE_CHANGE = nextMessageTypeId()
MessageType.AI_TASK_SKIPPED = nextMessageTypeId()
MessageType.RADIO_CHANNEL_CHANGE = nextMessageTypeId()
MessageType.APP_SUSPENDED = nextMessageTypeId()
MessageType.APP_RESUMED = nextMessageTypeId()
MessageType.APP_WINDOW_FOCUS_CHANGED = nextMessageTypeId()
MessageType.WINDOW_SIZE_CHANGED = nextMessageTypeId()
MessageType.DEBUG_MODE_CHANGED = nextMessageTypeId()
MessageType.STORAGE_ADDED_TO_UNLOADING_STATION = nextMessageTypeId()
MessageType.STORAGE_REMOVED_FROM_UNLOADING_STATION = nextMessageTypeId()
MessageType.STORAGE_ADDED_TO_LOADING_STATION = nextMessageTypeId()
MessageType.STORAGE_REMOVED_FROM_LOADING_STATION = nextMessageTypeId()
MessageType.HUSBANDRY_SYSTEM_ADDED_PLACEABLE = nextMessageTypeId()
MessageType.HUSBANDRY_SYSTEM_REMOVED_PLACEABLE = nextMessageTypeId()
MessageType.LOADED_ALL_SAVEGAME_HANDTOOLS = nextMessageTypeId()
MessageType.LOADED_ALL_SAVEGAME_VEHICLES = nextMessageTypeId()
MessageType.LOADED_ALL_SAVEGAME_PLACEABLES = nextMessageTypeId()
MessageType.START_GROWTH_PERIOD = nextMessageTypeId()
MessageType.FINISHED_GROWTH_PERIOD = nextMessageTypeId()
MessageType.AI_JOB_STARTED = nextMessageTypeId()
MessageType.AI_JOB_REMOVED = nextMessageTypeId()
MessageType.AI_JOB_STOPPED = nextMessageTypeId()
MessageType.TREE_SHAPE_CUT = nextMessageTypeId()
MessageType.TREE_SHAPE_MOUNTED = nextMessageTypeId()
MessageType.SLEEPING = nextMessageTypeId()
MessageType.SLOT_USAGE_CHANGED = nextMessageTypeId()
MessageType.INSETS_CHANGED = nextMessageTypeId()
MessageType.SPLIT_SHAPE = nextMessageTypeId()
MessageType.TRAFFIC_SYSTEM_LOADED = nextMessageTypeId()
MessageType.PEDESTRIAN_SYSTEM_LOADED = nextMessageTypeId()
MessageType.AI_SYSTEM_LOADED = nextMessageTypeId()
MessageType.ON_CLIENT_START_MISSION = nextMessageTypeId()
MessageType.ENQUEUED_ALL_LOADINGS = nextMessageTypeId()
