Shader = {}
Shader.PARAM_SHARED_WIND_SPEED = 0
Shader.PARAM_SHARED_WIND_DIR_X = 1
Shader.PARAM_SHARED_WIND_DIR_Z = 2
Shader.PARAM_SHARED_SEASON = 3
Shader.PARAM_SHARED_SNOW = 4
Shader.PARAM_SHARED_RAIN_SCALE = 5
