NPCText = {}
NPCText.FALLBACK_TEXT_SUFFIX = "_en"
NPCText.FALLBACK_AUDIO_SUFFIX = "_en"
NPCText.FALLBACK_EMOTION_SUFFIX = "_en"
local NPCText_mt = Class(NPCText)
g_xmlManager:addCreateSchemaFunction(function()
	NPCText.xmlSchema = XMLSchema.new("npcText")
end)
g_xmlManager:addInitSchemaFunction(function()
	local schema = NPCText.xmlSchema
	schema:register(XMLValueType.STRING, "text.emotional", "Emotional text (Sample: '[anger, low] TEXT [/anger]') (Available tags: anger, surprise, disgust, happiness, fear, sadness, confusion) (Available levels: low, medium, high, extreme)", nil, true)
	schema:register(XMLValueType.STRING, "text.silence", "The silence part of the text (autogenerated)", nil, false)
end)
function NPCText.new(isActive, customMt)
	local self = setmetatable({}, customMt or NPCText_mt)
	self.isActive = isActive
	self.isInitialized = false
	self.path = nil
	self.textFilename = nil
	self.audioFilename = nil
	self.emotionFilename = nil
	self.plainText = nil
	return self
end
function NPCText:load(path, isOption)
	self.path = path
	self.isOption = isOption
end
function NPCText:init()
	self.isInitialized = true
	local path = self.path
	local audioLanguage = g_languageSuffix
	local audioFilename = path .. audioLanguage .. ".wav"
	if not audioFileExists(audioFilename) then
		audioLanguage = NPCText.FALLBACK_AUDIO_SUFFIX
		audioFilename = path .. audioLanguage .. ".wav"
		if not audioFileExists(audioFilename) then
			audioFilename = nil
		end
	end
	self.audioFilename = audioFilename
	local emotionLanguage = g_languageSuffix
	local emotionFilename = path .. emotionLanguage .. ".bin"
	if not fileExists(emotionFilename) then
		emotionLanguage = NPCText.FALLBACK_EMOTION_SUFFIX
		emotionFilename = path .. emotionLanguage .. ".bin"
		if not fileExists(emotionFilename) then
			emotionFilename = nil
		end
	end
	self.emotionFilename = emotionFilename
	local textLanguage = g_languageSuffix
	local textFilename = path .. textLanguage .. ".xml"
	if not fileExists(textFilename) then
		textLanguage = NPCText.FALLBACK_TEXT_SUFFIX
		textFilename = path .. textLanguage .. ".xml"
	end
	local emotionalText = nil
	local xmlFile = XMLFile.loadIfExists("npcText", textFilename, NPCText.xmlSchema)
	if xmlFile ~= nil then
		emotionalText = xmlFile:getValue("text.emotional")
		if emotionalText == nil then
			emotionalText = string.format("Missing npc emotional text for '%s'", textFilename)
		elseif emotionalText == "TODO" then
			Logging.xmlDevWarning(xmlFile, "Missing translation for npc text")
		end
		self.plainText = NPCUtil.cleanEmotionalText(emotionalText)
		xmlFile:delete()
	else
		self.plainText = string.format("Could not open npc text file '%s'", textFilename)
		if self.isActive then
			Logging.warning("NPCText: Could not open npc text file '%s'", textFilename)
		end
	end
	if g_isDevelopmentVersion and self.isActive then
		if Platform.isPC and emotionFilename ~= nil then
			if emotionalText ~= nil and (emotionLanguage == textLanguage and not checkFacialAnimScript(emotionFilename, emotionalText)) then
				Logging.warning("NPCText: Emotions file '%s' is outdated. It does not match the text file '%s' anymore", emotionFilename, textFilename)
			end
			if audioFilename ~= nil and (emotionLanguage == audioLanguage and not checkFacialAnimAudioFile(emotionFilename, audioFilename)) then
				Logging.warning("NPCText: Audio file '%s' is outdated. It does not match the emotions '%s' anymore", audioFilename, emotionFilename)
			end
		end
		if not self.isOption then
			if g_languageSuffix == NPCText.FALLBACK_AUDIO_SUFFIX and audioFilename == nil then
				Logging.warning("NPCText: VoiceOver file is missing for text '%s'", textFilename)
			end
			if g_languageSuffix == NPCText.FALLBACK_EMOTION_SUFFIX and emotionFilename == nil then
				Logging.warning("NPCText: Emotion file is missing for text '%s'", textFilename)
			end
		end
	end
end
function NPCText:delete()
	self:reset()
end
function NPCText:reset()
	self.isInitialized = false
	self.textFilename = nil
	self.audioFilename = nil
	self.vismeFilename = nil
	self.plainText = nil
end
function NPCText:getPlainText()
	if not self.isInitialized then
		Logging.devWarning("NPCText is not initialized")
	end
	return self.plainText
end
function NPCText:getAudioFilename()
	if not self.isInitialized then
		Logging.devWarning("NPCText is not initialized")
	end
	return self.audioFilename
end
function NPCText:getEmotionFilename()
	if not self.isInitialized then
		Logging.devWarning("NPCText is not initialized")
	end
	return self.emotionFilename
end
