-- Local values: NPCText_mt
NPCText = {}
NPCText.FALLBACK_TEXT_SUFFIX = "_en"
NPCText.FALLBACK_AUDIO_SUFFIX = "_en"
NPCText.FALLBACK_EMOTION_SUFFIX = "_en"
local NPCText_mt = Class(NPCText)
g_xmlManager:addCreateSchemaFunction(function()
	NPCText.xmlSchema = XMLSchema.new("npcText")
end)
g_xmlManager:addInitSchemaFunction(function()
	local v2_ = NPCText.xmlSchema
	v2_:register(XMLValueType.STRING, "text.emotional", "Emotional text (Sample: \'[anger, low] TEXT [/anger]\') (Available tags: anger, surprise, disgust, happiness, fear, sadness, confusion) (Available levels: low, medium, high, extreme)", nil, true)
	v2_:register(XMLValueType.STRING, "text.silence", "The silence part of the text (autogenerated)", nil, false)
end)

-- Upvalues: NPCText_mt
-- Local values: self
function NPCText.new(isActive, customMt)
	-- upvalues: (copy) NPCText_mt
	local v5_ = customMt or NPCText_mt
	local v6_ = setmetatable({}, v5_)
	v6_.isActive = isActive
	v6_.isInitialized = false
	v6_.path = nil
	v6_.textFilename = nil
	v6_.audioFilename = nil
	v6_.emotionFilename = nil
	v6_.plainText = nil
	return v6_
end

function NPCText:load(path, isOption)
	self.path = path
	self.isOption = isOption
end

-- Local values: path, audioLanguage, audioFilename, emotionLanguage, emotionFilename, textLanguage, textFilename, emotionalText, xmlFile
function NPCText:init()
	self.isInitialized = true
	local v11_ = self.path
	local v12_ = g_languageSuffix
	local v13_ = v11_ .. v12_ .. ".wav"
	if not audioFileExists(v13_) then
		v12_ = NPCText.FALLBACK_AUDIO_SUFFIX
		v13_ = v11_ .. v12_ .. ".wav"
		if not audioFileExists(v13_) then
			v13_ = nil
		end
	end
	self.audioFilename = v13_
	local v14_ = g_languageSuffix
	local v15_ = v11_ .. v14_ .. ".bin"
	if not fileExists(v15_) then
		v14_ = NPCText.FALLBACK_EMOTION_SUFFIX
		v15_ = v11_ .. v14_ .. ".bin"
		if not fileExists(v15_) then
			v15_ = nil
		end
	end
	self.emotionFilename = v15_
	local v16_ = g_languageSuffix
	local v17_ = v11_ .. v16_ .. ".xml"
	if not fileExists(v17_) then
		v16_ = NPCText.FALLBACK_TEXT_SUFFIX
		v17_ = v11_ .. v16_ .. ".xml"
	end
	local v18_ = nil
	local v19_ = XMLFile.loadIfExists("npcText", v17_, NPCText.xmlSchema)
	if v19_ == nil then
		self.plainText = string.format("Could not open npc text file \'%s\'", v17_)
		if self.isActive then
			Logging.warning("NPCText: Could not open npc text file \'%s\'", v17_)
		end
	else
		v18_ = v19_:getValue("text.emotional")
		if v18_ == nil then
			v18_ = string.format("Missing npc emotional text for \'%s\'", v17_)
		elseif v18_ == "TODO" then
			Logging.xmlDevWarning(v19_, "Missing translation for npc text")
		end
		self.plainText = NPCUtil.cleanEmotionalText(v18_)
		v19_:delete()
	end
	if g_isDevelopmentVersion and self.isActive then
		if Platform.isPC and v15_ ~= nil then
			if v18_ ~= nil and (v14_ == v16_ and not checkFacialAnimScript(v15_, v18_)) then
				Logging.warning("NPCText: Emotions file \'%s\' is outdated. It does not match the text file \'%s\' anymore", v15_, v17_)
			end
			if v13_ ~= nil and (v14_ == v12_ and not checkFacialAnimAudioFile(v15_, v13_)) then
				Logging.warning("NPCText: Audio file \'%s\' is outdated. It does not match the emotions \'%s\' anymore", v13_, v15_)
			end
		end
		if not self.isOption then
			if g_languageSuffix == NPCText.FALLBACK_AUDIO_SUFFIX and v13_ == nil then
				Logging.warning("NPCText: VoiceOver file is missing for text \'%s\'", v17_)
			end
			if g_languageSuffix == NPCText.FALLBACK_EMOTION_SUFFIX and v15_ == nil then
				Logging.warning("NPCText: Emotion file is missing for text \'%s\'", v17_)
			end
		end
	end
end

function NPCText:delete()
	self:reset()
end

function NPCText:reset()
	self.isInitialized = false
	self.textFilename = nil
	self.audioFilename = nil
	self.vismeFilename = nil
	self.plainText = nil
end

function NPCText:getPlainText()
	if not self.isInitialized then
		Logging.devWarning("NPCText is not initialized")
	end
	return self.plainText
end

function NPCText:getAudioFilename()
	if not self.isInitialized then
		Logging.devWarning("NPCText is not initialized")
	end
	return self.audioFilename
end

function NPCText:getEmotionFilename()
	if not self.isInitialized then
		Logging.devWarning("NPCText is not initialized")
	end
	return self.emotionFilename
end
